/*
-----------------------------------------------------------------------------
Filename:    OgreVishesh.cpp
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.8.x Application Wizard for VC10 (May 2012)
      https://bitbucket.org/jacmoe/ogreappwizards
-----------------------------------------------------------------------------
*/

#include "../include/OgreVishesh.h"
#include<iostream>


OgreVisheshFrameListener:: OgreVisheshFrameListener(Ogre::SceneNode* node)
{
  _node=node;
} 

OgreVisheshFrameListener:: OgreVisheshFrameListener(void)
{
	FrameListener = NULL;
}

OgreVisheshFrameListener::~ OgreVisheshFrameListener(void)
{
	if(FrameListener)
	{
		delete FrameListener;
	}
}

bool OgreVisheshFrameListener::frameStarted(const Ogre:: FrameEvent &evt)
{
	_node->translate(Ogre::Vector3(1000,0,0) * evt.timeSinceLastEvent);
	return true;
}


//-------------------------------------------------------------------------------------
OgreVishesh::OgreVishesh(void)
{
}
//-------------------------------------------------------------------------------------
OgreVishesh::~OgreVishesh(void)
{
}

void OgreVishesh::createFrameListener(void)
{
	Ogre::
		FrameListener *FrameListener=new OgreVisheshFrameListener(_SinbadNode);
	mRoot->addFrameListener(FrameListener);
}

void OgreVishesh::createCamera(void)
{
	mCamera= mSceneMgr->createCamera("MyCam");
    mCamera->setPosition(0,100,200);
	mCamera->lookAt(0,0,0);
	mCamera->setNearClipDistance(5);
	mCameraMan = new OgreBites::SdkCameraMan(mCamera);	
}

//-------------------------------------------------------------------------------------
void OgreVishesh::createScene(void)
{
	Ogre::Plane plane(Ogre::Vector3::UNIT_Y,-10);
	Ogre::MeshManager::getSingleton().createPlane("plane",Ogre::ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME,plane,
													1500,1500,20,20,true,1,5,5,Ogre::Vector3::UNIT_Z);
	Ogre::Entity* ent1=mSceneMgr->createEntity("LightPlaneEntity","plane");
	mSceneMgr->getRootSceneNode()->createChildSceneNode()->attachObject(ent1);
	ent1->setMaterialName("Examples/BeachStones");

	Ogre::Light* light1=mSceneMgr->createLight("Light1");
	light1->setType(Ogre::Light::LT_DIRECTIONAL);
	light1->setDirection(Ogre::Vector3(1,-1,0));

	 Ogre::SceneNode* node1=mSceneMgr->createSceneNode("node1");
	 mSceneMgr->getRootSceneNode()->addChild(node1);
	 Ogre::Entity* sinbad = mSceneMgr->createEntity("sinbad", "Sinbad.mesh");
	 _SinbadNode = node1->createChildSceneNode("sinbadnode",Ogre::Vector3(0,4,0));
	 _SinbadNode->setScale(3,3,3);
	 _SinbadNode->attachObject(sinbad);

	 mSceneMgr->setShadowTechnique((Ogre::SHADOWTYPE_STENCIL_ADDITIVE));

	 std::cout<<"VISHESH";
}



#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#define WIN32_LEAN_AND_MEAN
#include "windows.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
    INT WINAPI WinMain( HINSTANCE hInst, HINSTANCE, LPSTR strCmdLine, INT )
#else
    int main(int argc, char *argv[])
#endif
    {
        // Create application object
        OgreVishesh app;

        try {
            app.go();
        } catch( Ogre::Exception& e ) {
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
            MessageBox( NULL, e.getFullDescription().c_str(), "An exception has occured!", MB_OK | MB_ICONERROR | MB_TASKMODAL);
#else
            std::cerr << "An exception has occured: " <<
                e.getFullDescription().c_str() << std::endl;
#endif
        }

        return 0;
    }

#ifdef __cplusplus
}
#endif
